<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DummyAssetController extends Controller
{
    public function queryAsset(Request $request) {
		$response 		= 'OK';
		$status_code 	= 200;
		$message			= 'Success';
		$result				= [];

		$qry = $request->input('q');
		$qry = strtoupper($qry);

		$jsonstring = '[{
          "id": "AAASbjAGiAAAA21AAJ",
          "name": "42161-DPS00001-27-FCV1301",
          "description": "BJN-FCV Flow Control Valve (52-FCV-1301)",
          "criticality": null,
          "category": "VA.FCV",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.539",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA22AAW",
          "name": "42161-DPS00001-27-BV1327",
          "description": "BJN-BV Ball Valve (52-BV-1327)",
          "criticality": null,
          "category": "VALVES - BALL",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.537",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA23AAC",
          "name": "42161-DPS00001-27-BV1345B",
          "description": "BJN-BV Ball Valve (52-BV-1345B)",
          "criticality": null,
          "category": "VALVES - BALL",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.537",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA23AAF",
          "name": "42161-DPS00001-27-BV1346",
          "description": "BJN-BV Ball Valve (52-BV-1346)",
          "criticality": null,
          "category": "VALVES - BALL",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.537",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA23AAI",
          "name": "42161-DPS00001-27-BV2101",
          "description": "BJN-BV Ball Valve (52-BV-2101)",
          "criticality": null,
          "category": "VALVES - BALL",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.538",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA23AAM",
          "name": "42161-DPS00001-27-BV2103",
          "description": "BJN-BV Ball Valve (52-BV-2103)",
          "criticality": null,
          "category": "VALVES - BALL",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.538",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA23AAO",
          "name": "42161-DPS00001-27-BV2104",
          "description": "BJN-BV Ball Valve (52-BV-2104)",
          "criticality": null,
          "category": "VALVES - BALL",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.538",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA23AAR",
          "name": "42161-DPS00001-27-BV2109",
          "description": "BJN-BV Ball Valve (52-BV-2109)",
          "criticality": null,
          "category": "VALVES - BALL",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.538",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA23AAU",
          "name": "42161-DPS00001-27-CKV2103",
          "description": "BJN-CKV Check Valve (52-CKV-2103)",
          "criticality": null,
          "category": "VALVES - CHECK",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.539",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA24AAA",
          "name": "42161-DPS00001-27-GV1303",
          "description": "BJN-GV Gate Valve (52-GV-1303)",
          "criticality": null,
          "category": "VALVES - GATE",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.539",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA24AAD",
          "name": "42161-DPS00001-27-GV1304",
          "description": "BJN-GV Gate Valve (52-GV-1304)",
          "criticality": null,
          "category": "VALVES - GATE",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.539",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        },
        {
          "id": "AAASbjAGiAAAA24AAN",
          "name": "42161-DPS00001-27-PLV1303",
          "description": "BJN-PLV Plug Valve (52-PLV-1303)",
          "criticality": null,
          "category": "VALVES - PLUG",
          "group": "VALVES",
          "location_id": "487",
          "location": "BOJONEGARA",
          "area_id": null,
          "area": "JAWA BAGIAN BARAT",
          "load_at": "2022-06-06 06:00:10.541",
          "created_at": null,
          "updated_at": null,
          "inventory_item_id": 36308,
          "owning_department_code": "BJN MAINT",
          "attribute_category": null,
          "manufacture": null,
          "model": null,
          "manufacture_part_number": null,
          "serial_number": null,
          "drawing_number": null,
          "installation_date": null
        }]';
        
        $result = json_decode($jsonstring, TRUE);
		
        if (!empty($qry)) {
            $result = array_filter($result, function($arr) use ($qry) {
                // Check if the query is a substring in either the name or description
                return stripos($arr['name'], $qry) !== false || stripos($arr['description'], $qry) !== false;
            });
        }

		return response()->json([
			'response'		=> $response,
			'status_code'	=> $status_code,
			'message'			=> $message,
			'result'			=> array_values($result),
		]);
	}
}
